print("Multipliction")
print("this is a calculator for multiplication")
number1= input("enter first number : ")
number2 = input("enter second number : ")
print(int(number1)*int(number2))

print("addition")
print("this is a calculator for addition")
number1= input("enter first number : ")
number2 = input("enter second number : ")
print(int(number1)+int(number2))

print("substraction")
print("this is a calculator for substraction")
number1= input("enter first number : ")
number2 = input("enter second number : ")
print(int(number1)-int(number2))

print("divide")
print("this is a calculator for divide")
number1= input("enter first number : ")
number2 = input("enter second number : ")
print(int(number1)/int(number2))
print("😁")
